In [11]:
import pandas as pd
import openpyxl

data = pd.read_csv("personality_dataset.csv")
data.head()

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,3,Yes,6,7,No,14,5,Extrovert
1,2,No,8,6,No,7,8,Extrovert
2,1,No,9,4,No,9,3,Extrovert
3,8,No,0,0,Yes,9,3,Introvert
4,5,Yes,3,0,No,2,6,Introvert

In [ ]:
#Convert personality to binary variable
# 1 for extrovert, 0 for introvert
data['Personality'] = data['Personality'].apply(lambda x: 1 if x == 'Extrovert' else 0) #Make sure this is converted for front_end
data['Stage_fear'] = data['Stage_fear'].apply(lambda x: 1 if x == 'Yes' else 0) #Make sure this is converted after input
data['Drained_after_socializing'] = data['Drained_after_socializing'].apply(lambda x: 1 if x == 'Yes' else 0) #Make sure this is converted after input

data

,Time_spent_Alone,Stage_fear,Social_event_attendance,Going_outside,Drained_after_socializing,Friends_circle_size,Post_frequency,Personality
0,3,1,6,7,0,14,5,1
1,2,0,8,6,0,7,8,1
2,1,0,9,4,0,9,3,1
3,8,0,0,0,1,9,3,0
4,5,1,3,0,0,2,6,0
...,...,...,...,...,...,...,...,...
4995,5,0,6,5,0,14,8,1
4996,7,0,2,3,1,2,5,0
4997,2,0,7,3,0,11,3,1
4998,2,1,9,3,0,15,7,1
4999,4,1,6,7,0,12,3,1

In [14]:
#Implement logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


X = data.drop(columns=['Personality'])
y = data['Personality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.986
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       500
           1       0.98      0.99      0.99       500

    accuracy                           0.99      1000
   macro avg       0.99      0.99      0.99      1000
weighted avg       0.99      0.99      0.99      1000

[[491   9]
 [  5 495]]